# Generated by Django 4.0.2 on 2022-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('email', models.CharField(default='', max_length=255, unique=True, verbose_name='이메일')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
